name: test

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  msys2:
    runs-on: windows-latest
    strategy:
      matrix:
        qt-version: [qt5, qt6]

    steps:
    - name: Setup MSYS2 Environment
      uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        update: true
        install: >-
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-${{ matrix.qt-version }}

    - name: Checkout
      uses: actions/checkout@v4

    - name: Build and test
      shell: msys2 {0}
      run: |
        cd demo/
        cmake .
        cmake --build . --parallel $(nproc)
        ./demo.exe
        cat conf.json
